#![no_std]
#![no_main]
extern crate alloc;

use esp_alloc as _;
use esp_backtrace as _;
use embassy_executor::Spawner;
use esp_hal::{
    clock::CpuClock,
    interrupt::software::SoftwareInterruptControl,
    timer::timg::TimerGroup,
};
use static_cell::StaticCell;

const PLATFORM_ID: u32 = {PLATFORM_ID};
{MTLS_CERTS}
{NETWORK_CONSTANTS}

// ── Per-bus CAN task definitions (generated by xtask) ────────────────────────
{CORE1_CAN_TASK_DEFS}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    esp_println::logger::init_logger_from_env();
    esp_alloc::heap_allocator!(size: 72 * 1024);

    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);
    let timg0 = TimerGroup::new(peripherals.TIMG0);

    let sw_int = SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);
    esp_rtos::start(timg0.timer0);

    core_interface::init(PLATFORM_ID);

    // ── Network: WiFi init ────────────────────────────────────────────────
{NETWORK_HARDWARE_INIT}
    // ── CAN driver initialisation (generated by xtask) ────────────────────
{CAN_HARDWARE_INIT}
    // ── Core 1: CAN driver tasks ──────────────────────────────────────────
    static mut CORE1_STACK: esp_hal::system::Stack<8192> = esp_hal::system::Stack::new();
    static CORE1_EXECUTOR: StaticCell<esp_rtos::embassy::Executor> = StaticCell::new();

    esp_rtos::start_second_core(
        peripherals.CPU_CTRL,
        sw_int.software_interrupt0,
        sw_int.software_interrupt1,
        unsafe { &mut *&raw mut CORE1_STACK },
        move || {
            CORE1_EXECUTOR.init(esp_rtos::embassy::Executor::new()).run(|s: embassy_executor::Spawner| {
{CORE1_TASK_SPAWNS}            });
        },
    );

    // ── Core 0: comms + vehicle tasks ─────────────────────────────────────
    board_esp::start(&spawner);
{MQTT_DRIVER_SPAWN}    spawner.spawn({VEHICLE_CRATE_IDENT}::handle_basic_commands_task()).unwrap();
    spawner.spawn({VEHICLE_CRATE_IDENT}::handle_advanced_commands_task()).unwrap();
    spawner.spawn({VEHICLE_CRATE_IDENT}::state_update_task()).unwrap();
    spawner.spawn({VEHICLE_CRATE_IDENT}::can_rx_task()).unwrap();

    loop {
        embassy_time::Timer::after(embassy_time::Duration::from_secs(1)).await;
    }
}
