#![no_std]
#![no_main]
extern crate alloc;

use esp_alloc as _;
use esp_backtrace as _;
use embassy_executor::Spawner;
use esp_hal::{
    clock::CpuClock,
    timer::timg::TimerGroup,
};
use static_cell::StaticCell;

esp_bootloader_esp_idf::esp_app_desc!();

const PLATFORM_ID: u32 = {PLATFORM_ID};
{MTLS_CERTS}
{NETWORK_CONSTANTS}

// ── Per-bus CAN task definitions (generated by xtask) ────────────────────────
{CORE1_CAN_TASK_DEFS}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    esp_println::logger::init_logger_from_env();
    esp_alloc::heap_allocator!(size: 160 * 1024);

    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);
    let timg0 = TimerGroup::new(peripherals.TIMG0);

    esp_rtos::start(timg0.timer0, unsafe { esp_hal::interrupt::software::SoftwareInterrupt::<0>::steal() });

    core_interface::init(PLATFORM_ID);

    // ── Network: WiFi init ────────────────────────────────────────────────
{NETWORK_HARDWARE_INIT}
    // ── CAN driver initialisation (generated by xtask) ────────────────────
{CAN_HARDWARE_INIT}
    // ── Core 1: CAN driver tasks ──────────────────────────────────────────
    static CORE1_STACK: StaticCell<esp_hal::system::Stack<8192>> = StaticCell::new();
    static CORE1_EXECUTOR: StaticCell<esp_rtos::embassy::Executor> = StaticCell::new();

    esp_rtos::start_second_core(
        peripherals.CPU_CTRL,
        unsafe { esp_hal::interrupt::software::SoftwareInterrupt::<1>::steal() },
        CORE1_STACK.init(esp_hal::system::Stack::new()),
        move || {
            CORE1_EXECUTOR.init(esp_rtos::embassy::Executor::new()).run(|s: embassy_executor::Spawner| {
{CORE1_TASK_SPAWNS}            });
        },
    );

    // ── Core 0: comms + vehicle tasks ─────────────────────────────────────
    board_esp::start(&spawner);
{BLE_DRIVER_SPAWN}
    spawner
        .spawn(board_esp::ble_lifecycle_task(
            BLE_PAIRING_BUTTON_PIN,
            BLE_PAIRING_BUTTON_HOLD_S,
            BLE_PAIRING_WINDOW_S,
            BLE_MAX_BONDED_PHONES,
            BLE_CONTROLLER_LEASE_TTL_S,
        ).unwrap());
{MQTT_DRIVER_SPAWN}    spawner.spawn({VEHICLE_CRATE_IDENT}::handle_basic_commands_task().unwrap());
    spawner.spawn({VEHICLE_CRATE_IDENT}::handle_advanced_commands_task().unwrap());
    spawner.spawn({VEHICLE_CRATE_IDENT}::state_update_task().unwrap());
    spawner.spawn({VEHICLE_CRATE_IDENT}::can_rx_task().unwrap());

    loop {
        embassy_time::Timer::after(embassy_time::Duration::from_secs(1)).await;
    }
}
