#![no_std]
#![no_main]
extern crate alloc;

use esp_alloc as _;
use esp_backtrace as _;
use embassy_executor::Spawner;
use esp_hal::{
    clock::CpuClock,
    timer::timg::TimerGroup,
};

esp_bootloader_esp_idf::esp_app_desc!();

const PLATFORM_ID: u32 = {PLATFORM_ID};
{MTLS_CERTS}
{NETWORK_CONSTANTS}

// ── Per-bus CAN task definitions (generated by xtask) ────────────────────────
{CAN_TASK_DEFS}

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    esp_println::logger::init_logger_from_env();
    log::info!("Booting firmware for vehicle platform: {}", stringify!({VEHICLE_CRATE_IDENT}));
    esp_alloc::heap_allocator!(size: {HEAP_SIZE});

    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);
    let timg0 = TimerGroup::new(peripherals.TIMG0);

    esp_rtos::start(timg0.timer0, unsafe { esp_hal::interrupt::software::SoftwareInterrupt::<0>::steal() });

    core_interface::init(PLATFORM_ID);

    // ── Network: WiFi init ────────────────────────────────────────────────
{NETWORK_HARDWARE_INIT}
    // ── CAN driver initialisation (generated by xtask) ────────────────────
{CAN_HARDWARE_INIT}
    // ── CAN driver tasks ──────────────────────────────────────────────────
{CAN_DRIVER_SPAWN}
    // ── Comms + vehicle tasks ─────────────────────────────────────────────
    board_esp::start(&spawner);
{BLE_DRIVER_SPAWN}
    spawner
        .spawn(board_esp::ble_lifecycle_task(
            BLE_PAIRING_BUTTON_PIN,
            BLE_PAIRING_BUTTON_HOLD_S,
            BLE_PAIRING_WINDOW_S,
            BLE_MAX_BONDED_PHONES,
            BLE_CONTROLLER_LEASE_TTL_S,
        ).unwrap());
{MQTT_DRIVER_SPAWN}    spawner.spawn({VEHICLE_CRATE_IDENT}::handle_basic_commands_task().unwrap());
    spawner.spawn({VEHICLE_CRATE_IDENT}::handle_advanced_commands_task().unwrap());
    spawner.spawn({VEHICLE_CRATE_IDENT}::state_update_task().unwrap());
    spawner.spawn({VEHICLE_CRATE_IDENT}::can_rx_task().unwrap());

    loop {
        embassy_time::Timer::after(embassy_time::Duration::from_secs(1)).await;
    }
}
