// ── On-hardware test binary (generated by `cargo xtask test --board esp --on-hardware`) ──
//
// Uses `embedded-test` with Embassy executor. Flash and run via probe-rs:
//   cargo xtask test --board esp --on-hardware
//
// Results are reported via semihosting. Each `#[test]` maps to a probe-rs
// test case; a panic (e.g. from `assert!`) counts as a test failure.

#![no_std]
#![no_main]
extern crate alloc;

use esp_alloc as _;

esp_bootloader_esp_idf::esp_app_desc!();

use esp_hal::{clock::CpuClock, timer::timg::TimerGroup};

#[embedded_test::tests(executor = esp_rtos::embassy::Executor::new())]
mod tests {
    use super::*;
    use embedded_can::{Id, StandardId};
    use core_interface::{CanFilter, CanFrame};

    /// One-time board init — runs before any test.
    #[init]
    fn init() {
        let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
        let peripherals = esp_hal::init(config);
        let timg0 = TimerGroup::new(peripherals.TIMG0);
        esp_rtos::start(timg0.timer0);
        esp_alloc::heap_allocator!(size: 72 * 1024);
        core_interface::init({PLATFORM_ID});
    }

    // ── core-interface channel smoke test ────────────────────────────────────

    /// Send a message on BASIC_CMD_CHANNEL and verify it arrives.
    #[test]
    async fn basic_cmd_channel_roundtrip() {
        use core_interface::{InboundCommand, Transport, BASIC_CMD_CHANNEL};
        let cmd = InboundCommand {
            message_id: 1,
            transport: Transport::Ble,
            source_device_id: alloc::vec![],
            bytes: alloc::vec![0xDE, 0xAD],
        };
        BASIC_CMD_CHANNEL.sender().send(cmd).await;
        let received = BASIC_CMD_CHANNEL.receiver().receive().await;
        assert_eq!(received.message_id, 1);
    }

    // ── passes_filter on-hardware smoke test ────────────────────────────────

    #[test]
    fn passes_filter_accepts_matching_frame() {
        let filters = [CanFilter {
            bus_id: 0,
            id: Id::Standard(StandardId::new(0x100).unwrap()),
            mask: 0x7FF,
        }];
        let frame = CanFrame {
            bus_id: 0,
            id: Id::Standard(StandardId::new(0x100).unwrap()),
            data: [0u8; 8],
            dlc: 0,
        };
        assert!(core_interface::passes_filter(&frame, &filters));
    }

    #[test]
    fn passes_filter_rejects_non_matching_frame() {
        let filters = [CanFilter {
            bus_id: 0,
            id: Id::Standard(StandardId::new(0x100).unwrap()),
            mask: 0x7FF,
        }];
        let frame = CanFrame {
            bus_id: 0,
            id: Id::Standard(StandardId::new(0x200).unwrap()),
            data: [0u8; 8],
            dlc: 0,
        };
        assert!(!core_interface::passes_filter(&frame, &filters));
    }

    // ── User-defined on-hardware tests (boards/esp/tests/hardware.rs) ────────
    {ON_HARDWARE_TESTS}
}
