use crate::{Config, TargetBuilder};
use serde::Deserialize;
use std::fs;
use std::path::Path;
use std::process::{Command, exit};

const EMBUILD_VERSION: &str = "0.33.0";
const DEFAULT_ESP_IDF_SVC_VERSION: &str = "0.52.1";

#[derive(Deserialize)]
struct EspConfig {
    mcu: String,
    can_tx_pin: u8,
    can_rx_pin: u8,
    modem_tx_pin: u8,
    modem_rx_pin: u8,
}

pub struct Builder;

impl Builder {
    // Helper method to dynamically extract and parse the ESP hardware config
    fn get_esp_config(config: &Config) -> EspConfig {
        config.hardware.get("esp")
            .expect("❌ Missing [hardware.esp] section in config")
            .clone()
            .try_into() // Converts the raw toml::Value into our EspConfig struct
            .expect("❌ Invalid [hardware.esp] config format")
    }

    // Helper method to share the complex toolchain and target logic between build and run
    fn execute_cargo_command(&self, config: &Config, cargo_cmd: &str) {
        let mut cmd = Command::new("cargo");
        cmd.arg("+esp").current_dir(".app_build").arg(cargo_cmd).arg("--release");

        let esp_hw = Self::get_esp_config(config);
        let mcu = &esp_hw.mcu;
        let target_arch = match mcu.as_str() {
            "esp32" => "xtensa-esp32-espidf",
            "esp32s2" => "xtensa-esp32s2-espidf",
            "esp32s3" => "xtensa-esp32s3-espidf",
            "esp32c3" => "riscv32imc-esp-espidf",
            "esp32c6" => "riscv32imac-esp-espidf",
            _ => unreachable!(),
        };
        cmd.arg("--target").arg(target_arch);
        cmd.arg("-Zbuild-std=std,panic_abort");
        cmd.env("MCU", mcu);

        let status = cmd.status().expect("Failed to execute cargo command");
        if !status.success() {
            exit(status.code().unwrap_or(1));
        }
    }
}

impl TargetBuilder for Builder {
    fn validate(&self, config: &Config) {
        let esp = Self::get_esp_config(config);
        if esp.mcu == "esp32s2" {
            eprintln!("❌ Error: The ESP32-S2 chip does not have Bluetooth/BLE capabilities. This project strictly requires BLE for phone app configuration and control.");
            exit(1);
        }
        let supported_mcus = ["esp32", "esp32s3", "esp32c3", "esp32c6"];
        if !supported_mcus.contains(&esp.mcu.as_str()) {
            eprintln!("❌ Error: Unsupported ESP MCU '{}'. Supported MCUs are: {:?}", esp.mcu, supported_mcus);
            exit(1);
        }
    }

    fn generate_cargo_config(&self, config: &Config) {
        let cargo_dir = Path::new(".app_build/.cargo");
        if !cargo_dir.exists() {
            fs::create_dir_all(cargo_dir).expect("Failed to create .app_build/.cargo directory");
        }

        let esp_hw = Self::get_esp_config(config);
        let mcu = esp_hw.mcu.as_str();

        let target = match mcu {
            "esp32s2" => "xtensa-esp32s2-espidf",
            "esp32s3" => "xtensa-esp32s3-espidf",
            "esp32c3" => "riscv32imc-esp-espidf",
            "esp32c6" => "riscv32imac-esp-espidf",
            _ => "xtensa-esp32-espidf",
        };

        let firmware_name = format!("open-car-firmware-{}-0.1.0.bin", mcu);
        fs::write(
            ".app_build/runner.sh",
            format!("#!/bin/sh\nespflash save-image --chip {} --merge \"$1\" {}\n", mcu, firmware_name)
        ).expect("Failed to write runner.sh");

        let config_toml_content = format!(
            r#"# --- AUTO-GENERATED BY XTASK ---
[build]
target = "{0}"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "sh runner.sh"
rustflags = [ "--cfg", "espidf_time64" ]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "{1}"
"#,
            target, mcu
        );

        fs::write(".app_build/.cargo/config.toml", config_toml_content)
            .expect("Failed to write config.toml");
    }

    fn extend_cargo_toml(&self, _config: &Config, toml: &mut String) {
        let board_toml_str = fs::read_to_string("boards/esp/Cargo.toml")
            .expect("Failed to read board Cargo.toml");
        let board_toml: toml::Value = toml::from_str(&board_toml_str)
            .expect("Failed to parse board Cargo.toml");
        let svc_version = board_toml.get("dependencies")
            .and_then(|d| d.get("esp-idf-svc"))
            .and_then(|v| v.as_str())
            .unwrap_or(DEFAULT_ESP_IDF_SVC_VERSION);

        toml.push_str(&format!("esp-idf-svc = \"{svc_version}\"\n\n"));
        toml.push_str("[build-dependencies]\n");
        toml.push_str(&format!("embuild = {{ version = \"{EMBUILD_VERSION}\", features = [\"espidf\"] }}\n"));
        
        fs::write(".app_build/build.rs", "fn main() { embuild::espidf::sysenv::output(); }\n")
            .expect("Failed to write build.rs");
    }

    fn generate_main_rs(&self, config: &Config, main_rs: &mut String) {
        let esp_hw = Self::get_esp_config(config);
        let platform = config.target.platform.replace("-", "_");

        let template = include_str!("main.template.rs");
        let generated = template
            .replace("{CAN_TX_PIN}", &esp_hw.can_tx_pin.to_string())
            .replace("{CAN_RX_PIN}", &esp_hw.can_rx_pin.to_string())
            .replace("{MODEM_TX_PIN}", &esp_hw.modem_tx_pin.to_string())
            .replace("{MODEM_RX_PIN}", &esp_hw.modem_rx_pin.to_string())
            .replace("{PLATFORM}", &platform);

        main_rs.push_str(&generated);
    }

    fn compile(&self, config: &Config) {
        println!("⚙️  Compiling the final firmware in .app_build/...");
        self.execute_cargo_command(config, "build");
        println!("✅ Firmware built successfully!");
    }

    // Override the default generic run method to use the ESP-specific toolchain
    fn run(&self, config: &Config) {
        println!("🚀 Running the firmware build pipeline...");
        self.execute_cargo_command(config, "run");
        println!("✅ Firmware image successfully generated!");
    }

    // Override the default clippy method to use the ESP-specific toolchain
    fn clippy(&self, config: &Config) {
        println!("🔍 Running clippy on the firmware build pipeline...");
        self.execute_cargo_command(config, "clippy");
        println!("✅ Clippy checks completed!");
    }
}
