use crate::{Config, TargetBuilder};
use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;
use std::process::{Command, exit};

#[derive(Deserialize)]
struct EspConfig {
    mcu: String,
    can_tx_pin: u8,
    can_rx_pin: u8,
    modem_tx_pin: u8,
    modem_rx_pin: u8,
    led_pin: u8,
    blink_interval_ms: u64,
}

pub struct Builder;

impl Builder {
    // Helper method to dynamically extract and parse the ESP hardware config
    fn get_esp_config(config: &Config) -> EspConfig {
        config.hardware.get("esp")
            .expect("❌ Missing [hardware.esp] section in config")
            .clone()
            .try_into() // Converts the raw toml::Value into our EspConfig struct
            .expect("❌ Invalid [hardware.esp] config format")
    }

    fn execute_cargo_command(&self, config: &Config, cargo_cmd: &str) {
        let esp_hw = Self::get_esp_config(config);
        let mcu = &esp_hw.mcu;

        let target_arch = match mcu.as_str() {
            "esp32" => "xtensa-esp32-none-elf",
            "esp32s2" => "xtensa-esp32s2-none-elf",
            "esp32s3" => "xtensa-esp32s3-none-elf",
            "esp32c3" => "riscv32imc-unknown-none-elf",
            "esp32c6" => "riscv32imac-unknown-none-elf",
            _ => unreachable!(),
        };

        let mut cmd = Command::new("cargo");

        if target_arch.starts_with("xtensa") {
            cmd.arg("+esp");
            cmd.arg("-Zbuild-std=core,alloc");
        }

        cmd.arg(cargo_cmd)
            .arg("-p").arg("board-esp")
            .arg("--target").arg(target_arch)
            .arg("--release");

        let features = format!("esp-hal/{mcu},esp-rtos/{mcu},esp-backtrace/{mcu},esp-println/{mcu}");
        cmd.arg("--features").arg(features);

        // Pass the esp-hal linker script that chains memory.x → esp32sX.x → hal-defaults.x → device.x
        // device.x provides PROVIDE() stubs for all peripheral interrupt symbols.
        cmd.env(
            "RUSTFLAGS",
            "-C link-arg=-Tlinkall.x",
        );

        let status = cmd.status().expect("Failed to execute cargo command");
        if !status.success() {
            exit(status.code().unwrap_or(1));
        }
    }
}

impl TargetBuilder for Builder {
    fn validate(&self, config: &Config) {
        let esp = Self::get_esp_config(config);
        if esp.mcu == "esp32s2" {
            eprintln!("❌ Error: The ESP32-S2 chip does not have Bluetooth/BLE capabilities. This project strictly requires BLE for phone app configuration and control.");
            exit(1);
        }
        let supported_mcus = ["esp32", "esp32s3", "esp32c3", "esp32c6"];
        if !supported_mcus.contains(&esp.mcu.as_str()) {
            eprintln!("❌ Error: Unsupported ESP MCU '{}'. Supported MCUs are: {:?}", esp.mcu, supported_mcus);
            exit(1);
        }
    }

    fn generate_config_rs(&self, config: &Config) {
        let esp_hw = Self::get_esp_config(config);

        let mut generated = String::from("// --- AUTO-GENERATED BY XTAST ---\n\n");

        generated.push_str(&format!(
            "macro_rules! get_can_tx_pin {{ ($p:expr) => {{ $p.GPIO{} }} }} \n\
            pub(crate) use get_can_tx_pin;\n\n", esp_hw.can_tx_pin
        ));

        generated.push_str(&format!(
            "macro_rules! get_can_rx_pin {{ ($p:expr) => {{ $p.GPIO{} }} }} \n\
            pub(crate) use get_can_rx_pin;\n\n", esp_hw.can_rx_pin
        ));

        generated.push_str(&format!(
            "macro_rules! get_led_pin {{ ($p:expr) => {{ $p.GPIO{} }} }} \n\
            pub(crate) use get_led_pin;\n\n", esp_hw.led_pin
        ));

        generated.push_str(&format!("pub const BLINK_INTERVAL_MS: u64 = {};\n\n", esp_hw.blink_interval_ms));

        let platform = config.target.platform.replace("-", "_");
        generated.push_str(&format!("pub const PLATFORM: &str = \"{}\";\n\n", platform));

        if config.network.mqtt.auth_mode == "mtls" {
            let ca = config.network.mqtt.ca_cert_file.as_ref().unwrap();
            let cert = config.network.mqtt.client_cert_file.as_ref().unwrap();
            let key = config.network.mqtt.client_key_file.as_ref().unwrap();

            generated.push_str(&format!("pub const CA_CERT: &[u8] = include_bytes!(\"../../../{}\");\n", ca));
            generated.push_str(&format!("pub const CLIENT_CERT: &[u8] = include_bytes!(\"../../../{}\");\n", cert));
            generated.push_str(&format!("pub const CLIENT_KEY: &[u8] = include_bytes!(\"../../../{}\");\n", key));
        }

        let out_dir = env::var_os("OUT_DIR").unwrap();
        let dest_path = Path::new(&out_dir).join("generated_config.rs");
        fs::write(&dest_path, generated).expect("Failed to write config");
    }

    fn compile(&self, config: &Config) {
        println!("⚙️ Compiling the bare-metal firmware...");
        self.execute_cargo_command(config, "build");
    }

    // Override the default generic run method to use the ESP-specific toolchain
    fn run(&self, config: &Config) {
        println!("🚀 Running the firmware build pipeline...");
        self.execute_cargo_command(config, "run");
    }

    // Override the default clippy method to use the ESP-specific toolchain
    fn clippy(&self, config: &Config) {
        println!("🔍 Running clippy on the firmware build pipeline...");
        self.execute_cargo_command(config, "clippy");
    }
}
