# ==============================================
#    OPEN CAR INTERFACE - BUILD CONFIGURATION
# ==============================================

[target]
# Select which board family you want to use. See the available boards in `boards/`
board = "esp"

# Select which brand and platform you want to use.
brand = "virtual-car"
platform = "virtual-car"

# ===================================
#    BOARD SPECIFIC CONFIGURATIONS
# ===================================

# Configuration for ESP family boards
[hardware.esp]
mcu = "esp32s3"
can_tx_pin = 5
can_rx_pin = 4
modem_tx_pin = 17
modem_rx_pin = 16
led_pin = 2
blink_interval_ms = 500

# Configuration for PC board
[hardware.pc]
can_interface = "can0"

# ===========================
#    NETWORK CONFIGURATION
# ===========================

[network.mqtt]
broker_url = "mqtts://192.168.0.100:8883"
client_id = "dev-car"

# Specify the type of authentication to the broker.
# - `basic` is for username/password combo
# - `mtls` is for using mTLS with certificates
auth_mode = "basic"

# Basic authentication configuration
username = "user"
password = "password"

# mTLS authentication configuration
ca_cert_file = "certs/ca.pem"
client_cert_file = "certs/client_cert.pem"
client_key_file = "certs/client_key.pem"
