use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Watch the boards directory so cargo automatically rebuilds xtask
    // if a new board folder is created or removed.
    println!("cargo:rerun-if-changed=../boards");

    let mut mods = String::new();
    let mut match_arms = String::new();

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let boards_dir = Path::new("../boards");
    if boards_dir.exists() {
        for entry in fs::read_dir(boards_dir).expect("Failed to read boards directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();

            if path.is_dir() {
                let board_name = path.file_name().unwrap().to_str().unwrap();
                let builder_file = path.join("xtask_builder.rs");

                if builder_file.exists() {
                    println!("cargo:rerun-if-changed={}", builder_file.display());

                    let abs_path = format!("{manifest_dir}/../boards/{board_name}/xtask_builder.rs")
                        .replace('\\', "/");

                    // Note: This path is evaluated relative to `xtask/src/main.rs` where the include! macro sits
                    mods.push_str(&format!(
                        "#[path = \"{abs_path}\"]\nmod board_{board_name};\n"
                    ));

                    match_arms.push_str(&format!(
                        "        \"{0}\" => Box::new(board_{0}::Builder),\n",
                        board_name
                    ));
                }
            }
        }
    }

    let generated_code = format!(
        r#"// --- AUTO-GENERATED BY XTASK BUILD SCRIPT ---
// DO NOT EDIT THIS FILE DIRECTLY

{mods}
pub fn get_builder(board: &str) -> Box<dyn TargetBuilder> {{
    match board {{
{match_arms}        _ => {{
            eprintln!("Error: Unsupported board '{{}}'. Did you create boards/{{}}/xtask_builder.rs?", board, board);
            std::process::exit(1);
        }}
    }}
}}"#
    );

    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("board_registry.rs");
    fs::write(&dest_path, generated_code).unwrap();
}
