use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;
use std::process::{Command, exit};

// ==========================================
// 1. TOML Configuration Data Models
// ==========================================

#[derive(Deserialize, Debug)]
pub struct Config {
    pub target: TargetConfig,
    pub hardware: toml::Value,
    pub network: NetworkConfig,
}

#[derive(Deserialize, Debug)]
pub struct TargetConfig {
    pub board: String, // e.g., "esp" or "rpi"
    pub brand: String,
    pub platform: String,
}

#[derive(Deserialize, Debug)]
pub struct NetworkConfig {
    pub mqtt: MqttConfig,
}

#[derive(Deserialize, Debug)]
pub struct MqttConfig {
    pub broker_url: String,
    pub client_id: String,
    pub auth_mode: String,
    // Used for mTLS
    pub ca_cert_file: Option<String>,
    pub client_cert_file: Option<String>,
    pub client_key_file: Option<String>,
    // Used for basic auth
    pub username: Option<String>,
    pub password: Option<String>,
}

// ==========================================
// 2. The Main CLI Entrypoint
// ==========================================

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 || (args[1] != "build" && args[1] != "run") {
        eprintln!("Usage: cargo xtask <build|run> [config_file.toml]");
        exit(1);
    }

    let command = &args[1];
    let config_path = if args.len() >= 3 {
        &args[2]
    } else {
        "config.toml"
    };
    println!("🚀 Starting custom {} using: {}", command, config_path);

    // Read and parse the config file
    let config_str = fs::read_to_string(config_path)
        .unwrap_or_else(|_| panic!("Failed to read config file: {}", config_path));
    let config: Config = toml::from_str(&config_str)
        .expect("Failed to parse TOML configuration");

    let builder = get_builder(&config.target.board);

    builder.validate(&config);

    // Run the pipeline
    scaffold_app_dir();
    builder.generate_cargo_config(&config);
    generate_cargo_toml(&config, &*builder);
    generate_main_rs(&config, &*builder);

    if command == "run" {
        builder.run(&config);
    } else {
        builder.compile(&config);
    }
}

// ==========================================
// 3. Platform Builders (Strategy Pattern)
// ==========================================

pub trait TargetBuilder {
    // Default implementation does nothing, can be overridden by boards that need a .cargo/config.toml
    fn generate_cargo_config(&self, _config: &Config) {}

    fn validate(&self, config: &Config);
    fn extend_cargo_toml(&self, config: &Config, toml: &mut String);
    fn generate_main_rs(&self, config: &Config, main_rs: &mut String);
    fn compile(&self, config: &Config);

    // Default implementation for running the project
    fn run(&self, _config: &Config) {
        let status = Command::new("cargo")
            .arg("run")
            .current_dir(".app_build")
            .status()
            .expect("Failed to execute cargo run");
        if !status.success() { exit(status.code().unwrap_or(1)); }
    }
}

// Automatically discovered and linked board builders
// This file is generated by xtask/build.rs.
include!("board_registry.rs");

// ==========================================
// 4. Application Generation Logic
// ==========================================

fn scaffold_app_dir() {
    let app_dir = Path::new(".app_build/src");
    if !app_dir.exists() {
        fs::create_dir_all(app_dir).expect("Failed to create .app_build/src directory");
    }

    // Clean up conditionally generated files to prevent cross-contamination between targets.
    // We intentionally leave the `target` directory alone to preserve Cargo's build cache!
    let _ = fs::remove_file(".app_build/build.rs");
    let _ = fs::remove_file(".app_build/runner.sh");
    
    // Delete any old generated .bin firmwares
    if let Ok(entries) = fs::read_dir(".app_build") {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("bin") {
                let _ = fs::remove_file(path);
            }
        }
    }
    let _ = fs::remove_dir_all(".app_build/.cargo");
}

fn generate_cargo_toml(config: &Config, builder: &dyn TargetBuilder) {
    // Dynamically link the requested board and car
    let mut cargo_toml_content = format!(
        r#"
# --- AUTO-GENERATED BY XTASK ---
[package]
name = "open-car-firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
core-interface = {{ path = "../core-interface" }}
board-{board} = {{ path = "../boards/{board}" }}
{platform}-controller = {{ path = "../cars/{brand}/platforms/{platform}" }}
"#,
        board = config.target.board,
        brand = config.target.brand,
        platform = config.target.platform
    );

    builder.extend_cargo_toml(config, &mut cargo_toml_content);

    fs::write(".app_build/Cargo.toml", cargo_toml_content)
        .expect("Failed to write Cargo.toml");
}

fn generate_main_rs(config: &Config, builder: &dyn TargetBuilder) {
    let mut main_rs = String::from("// --- AUTO-GENERATED BY XTASK ---\n\n");

    // --- Generate mTLS Cert Inclusions ---
    if config.network.mqtt.auth_mode == "mtls" {
        let ca = config.network.mqtt.ca_cert_file.as_ref().unwrap();
        let cert = config.network.mqtt.client_cert_file.as_ref().unwrap();
        let key = config.network.mqtt.client_key_file.as_ref().unwrap();
        
        // Note the ../../ to point back to the root of the workspace from .app_build/src
        main_rs.push_str(&format!("pub const CA_CERT: &[u8] = include_bytes!(\"../../{}\");\n", ca));
        main_rs.push_str(&format!("pub const CLIENT_CERT: &[u8] = include_bytes!(\"../../{}\");\n", cert));
        main_rs.push_str(&format!("pub const CLIENT_KEY: &[u8] = include_bytes!(\"../../{}\");\n\n", key));
    }

    builder.generate_main_rs(config, &mut main_rs);

    fs::write(".app_build/src/main.rs", main_rs)
        .expect("Failed to write main.rs");
}
