// ── User-defined on-hardware tests for board-esp ──────────────────────────────
//
// This file is injected verbatim into the `mod tests` block generated by
// `cargo xtask test --board esp --on-hardware`. Write additional `#[test]`
// functions here; they will run on the connected ESP32 via probe-rs.
//
// The `init()` in tests.template.rs already starts the ESP HAL, the Embassy
// executor (via esp_rtos), the heap allocator, and initialises core-interface.
// Board peripherals instantiated in `init()` can be passed to tests by
// returning them from `#[init]` as a struct.
//
// Example (TWAI loopback — requires the TX/RX pins to be shorted or a real bus):
//
// #[test]
// async fn twai_loopback_roundtrip() {
//     use core_interface::{CAN_RX_CHANNEL, CAN_TX_CHANNEL, CanFrame};
//     use embedded_can::{Id, StandardId};
//
//     let frame = CanFrame {
//         bus_id: 0,
//         id: Id::Standard(StandardId::new(0x123).unwrap()),
//         data: [1, 2, 3, 4, 0, 0, 0, 0],
//         dlc: 4,
//     };
//     CAN_TX_CHANNEL.sender().send(frame).await;
//
//     let timeout = embassy_time::Timer::after(embassy_time::Duration::from_millis(50));
//     let rx = embassy_futures::select::select(
//         CAN_RX_CHANNEL.receiver().receive(),
//         timeout,
//     ).await;
//     match rx {
//         embassy_futures::select::Either::First(received) => {
//             defmt::assert_eq!(received.id, frame.id);
//         }
//         embassy_futures::select::Either::Second(_) => {
//             defmt::panic!("CAN frame not received within 50 ms");
//         }
//     }
// }
