use crate::{Config, TargetBuilder};
use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;
use std::process::{Command, exit};

#[derive(Deserialize)]
struct RpiConfig {
    can_interface: String,
}

pub struct Builder;

impl Builder {
    // Helper method to dynamically extract and parse the PC hardware config
    fn get_pc_config(config: &Config) -> RpiConfig {
        config.hardware.get("pc")
            .expect("❌ Missing [hardware.pc] section in config")
            .clone()
            .try_into() // Converts the raw toml::Value into our RpiConfig struct
            .expect("❌ Invalid [hardware.pc] config format")
    }

    // Helper method to execute cargo against the persistent PC port crate
    fn execute_cargo_command(&self, cargo_cmd: &str) {
        let mut cmd = Command::new("cargo");
        
        // We target the workspace member directly.
        cmd.arg(cargo_cmd)
           .arg("-p").arg("board-pc") 
           .arg("--release");

        // Note: No `--target` flag is passed here, so it compiles natively 
        // for whatever host OS you are running xtask from (e.g., x86_64-unknown-linux-gnu).

        let status = cmd.status().expect("Failed to execute cargo command");
        if !status.success() {
            exit(status.code().unwrap_or(1));
        }
    }
}

impl TargetBuilder for Builder {
    fn validate(&self, _config: &Config) {
        // You can add validation here if needed (e.g., ensuring the OS is Linux 
        // if your PC simulator strictly relies on SocketCAN).
        if cfg!(windows) {
            println!("⚠️ Warning: Running PC simulator on Windows. Native SocketCAN will not be available.");
        }
    }

    fn generate_config_rs(&self, config: &Config) {
        let pc_hw = Self::get_pc_config(config);
        
        let mut generated = String::from("// --- AUTO-GENERATED BY XTASK ---\n\n");

        // Unlike ESP pins which are macros, the CAN interface on a PC 
        // is typically just a string identifier passed to the OS socket.
        generated.push_str(&format!(
            "pub const CAN_INTERFACE: &str = \"{}\";\n\n", 
            pc_hw.can_interface
        ));

        // Pass the selected platform as a constant
        let platform = config.target.platform.replace("-", "_");
        generated.push_str(&format!("pub const PLATFORM: &str = \"{}\";\n\n", platform));

        // Inject network secrets
        if config.network.mqtt.auth_mode == "mtls" {
            let ca = config.network.mqtt.ca_cert_file.as_ref().unwrap();
            let cert = config.network.mqtt.client_cert_file.as_ref().unwrap();
            let key = config.network.mqtt.client_key_file.as_ref().unwrap();

            // Paths are relative to the ports/pc/src directory
            generated.push_str(&format!("pub const CA_CERT: &[u8] = include_bytes!(\"../../../{}\");\n", ca));
            generated.push_str(&format!("pub const CLIENT_CERT: &[u8] = include_bytes!(\"../../../{}\");\n", cert));
            generated.push_str(&format!("pub const CLIENT_KEY: &[u8] = include_bytes!(\"../../../{}\");\n", key));
        }

        // Write the file into the permanent PC port directory
        let out_dir = env::var_os("OUT_DIR").unwrap();
        let dest_path = Path::new(&out_dir).join("generated_config.rs");
        fs::write(&dest_path, generated).expect("Failed to write config");
    }

    fn compile(&self, _config: &Config) {
        println!("⚙️  Compiling the PC simulator natively...");
        self.execute_cargo_command("build");
    }

    fn run(&self, _config: &Config) {
        println!("🚀 Running the PC simulator natively...");
        self.execute_cargo_command("run");
    }

    fn clippy(&self, _config: &Config) {
        println!("🔍 Running clippy on the PC simulator...");
        self.execute_cargo_command("clippy");
    }
}
